name: JustTPA
version: 1.2.0
main: com.flyaway.justtpa.JustTPA
api-version: 1.21
description: Кастомные сообщения телепортации игроков
author: FlyAwayMaking
website: https://github.com/flyawaymaking
softdepend:
  - Essentials

commands:
  justtpa:
    description: Перезагрузка конфига
    usage: /<command> <reload>
    permission: justtpa.reload
  tpa:
    description: Отправить запрос на телепортацию игроку
    usage: /tpa <player>
    permission: justtpa.tpa
  tpaccept:
    description: Принять запрос на телепортацию
    usage: /tpaccept <player>
    permission: justtpa.tpaccept
  tpdeny:
    description: Отклонить запрос на телепортацию
    usage: /tpdeny <player>
    permission: justtpa.tpdeny
  tpcancel:
    description: Отмените свой запрос на телепортацию
    usage: /tpcancel <player>
    permission: justtpa.tpcancel
  tpahere:
    description: Попросите игрока телепортироваться к вам
    usage: /tpahere <player>
    permission: justtpa.tpahere

permissions:
  justtpa.*:
    description: Все права плагина JustTPA
    children:
      justtpa.user: true
      justtpa.reload: true
  justtpa.user:
    description: Права для игроков
    children:
      justtpa.tpa: true
      justtpa.tpaccept: true
      justtpa.tpdeny: true
      justtpa.tpcancel: true
      justtpa.tpahere: true
  justtpa.tpa:
    description: Разрешить использование /tpa command
    default: true
  justtpa.tpaccept:
    description: Разрешить использование /tpaccept command
    default: true
  justtpa.tpdeny:
    description: Разрешить использование /tpdeny command
    default: true
  justtpa.tpcancel:
    description: Разрешить использование /tpcancel command
    default: true
  justtpa.tpahere:
    description: Разрешить использование /tpahere command
    default: true
  justtpa.reload:
    description: Разрешить использование /justtpa reload
    default: op
